model:
  meta_architecture: "RBSolver"
  rbsolver_iter:
    data_dir: data/franka/example
    use_realarm:
      enable: True
      ip: "172.16.0.2" # xarm ip
      speed: 0.1
      wait_time: 1 # wait time between arm stop and image capture
      speed_control: True
      safety_factor: 6 # safety factor for speed control, the larger, the safer
      timestep: 0.05
datasets:
  train: ("franka_real/franka/example",)
  test: "franka_real/franka/example"

solver:
  trainer: "rbsolver_iter"
  log_interval: 20
  explore_iters: 10 # the number of iterations for exploration
  num_epochs: 2000 # the number of iterations for optimization
  max_lr: 0.003 # the learning rate for optimization
  batch_size: 100 # a large number to make sure all the images are in one batch
  save_freq: 20
  val_freq: 20
  save_every: True
  save_mode: iteration
input:
  shuffle: False
dataloader:
  pin_memory: True
test:
  batch_size: 100

